### ISSUE TITLE
Provide a unique name while installing

### ISSUE THREAD

**Issue by thisthat** [keptn-contrib/helm-service#3]
## Tech details

Helm-service should provide a unique name while installing itself so that it can be easily installed in multiple remote-exec planes.
Users can still use `nameOverride` to provide their own name.

## Acceptance Criteria

- [ ] When installing, helm-service creates a random alphanumeric string of 10chars that's appended to the integration name used to subscribe to the Keptn control plane
- [ ] The generated string is stored in a ConfigMap
- [ ] If the ConfigMap already exists, helm-service uses the CM value instead of the generated one
- [ ] if `nameOverride` is set via Helm value, it has precedence over the generated name

## DoD

- [ ] Helm-service has a unique name on the Keptn control-plane when it is installed
- [ ] Updates of the integration do not change the integration name

## Resources 

Further information is available at https://github.com/keptn/keptn/issues/8576

**Comment by philipp-hinteregger** [comment]
This issue wasn't implemented like described, because it would be necessary to merge all helm resources into a single file.
Like described in [this](https://github.com/helm/helm-www/pull/877/files/6fbc48fb8a59ae7fa4b128c9035fb05781492b40) PR, a generated value would need to be in the same file as it's usage, since every invocation of the named template would regenerate the value.
Hence the implementation is discarded, and the README.md was updated in order to provide the necessary information for installations on multi remote execution plane setups, with the PR #9

**Comment by thisthat** [comment]
Thank you @philipp-hinteregger for the write-up!
